print("")
print("Hello there! Can I please take your name?")
print("")
your_name=input("Please enter your name: ")
print("")
print("Thank you, it's lovely to meet you", your_name)
print("")
your_age=input("How old are you"+ " " + your_name +"?")
print("Wow, you're" + " " + your_age + "!")
print("")
print("Hello, World!")