print("")
print("Welcome to your favourite restaurant!")
print("")
item_one=input("Please order your first favourite item: ")
print("")
item_two=input("Please order your second favourite item: ")
print("")
item_three=input("Please order your third favourite item: ")
print("")
print("Thank you for your order!, to confirm you have ordered the following:")
print(item_one)
print(item_two)
print(item_three)
